services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Walther\Hotwired\:
    resource: '../Classes/*'

  Walther\Hotwired\Backend\ToolbarItems\ServerStatusToolbarItem:
    public: true

  Walther\Hotwired\Command\ServerCommand:
    tags:
      - name: console.command
        command: 'hotwired:server:run'
        description: 'Starts the websocket server'
        schedulable: false
        hidden: true

  Walther\Hotwired\Command\ManageCommand:
    tags:
      - name: console.command
        command: 'hotwired:server:manage'
        description: 'Manages the websocket server'
        schedulable: false
        hidden: false
